INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('1', 'ACCIONES CONSTITUCIONALES', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('2', 'ACTAS ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('3', 'ACUERDOS ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('4', 'ARQUEOS DE CAJA', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('5', 'BALANCE GENERAL ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('6', 'BOLETINES ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('7', 'CERTIFICADOS', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('8', 'COMPROBANTES CONTABLES', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('9', 'COMUNICACIONES OFICIALES ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('10', 'CONCILIACIONES', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('11', 'CONCEPTOS', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('12', 'CONTRATOS ESTATALES ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('13', 'CONVENIOS ESTATALES ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('14', 'COPIAS DE SEGURIDAD ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('15', 'CUENTAS POR PAGAR', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('16', 'DECLARACIONES TRIBUTARIAS', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('17', 'ESCRITURAS PÚBLICAS', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('18', 'ESTADOS FINANCIEROS', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('19', 'ESTUDIOS', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('20', 'FACTURAS', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('21', 'HISTORIAS ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('22', 'INFORMES', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('23', 'INSTRUMENTOS DE CONTROL ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('24', 'INSTRUMENTOS DE GESTION DOCUMENTAL', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('25', 'INSTRUMENTOS DEL MODELO INTEGRADO DE PLANEACION Y GESTION MIPG', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('26', 'INSTRUMENTOS DEL SISTEMA DE SEGURIDAD Y SALUD EN EL TRABAJO SST', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('27', 'INVENTARIOS', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('28', 'LIBROS  CONTABLES', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('29', 'LICENCIAS', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('30', 'MANUALES ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('31', 'NOMINA ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('32', 'ORDENES', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('33', 'PQRSFD-PETICIONES, QUEJAS, RECLAMOS, DENUNCIAS Y SEGURENCIAS ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('34', 'PLANES', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('35', 'PRESUPUESTO ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('36', 'PROGRAMAS', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('37', 'PROYECTOS ', 1);
INSERT INTO `archivo_trd_series` (`cod_serie`, `nom_serie`,`acti`) VALUES('38', 'RESOLUCIONES', 1);
