INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Acciones de Tutela', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Actas Comité Institucional de Gestión y Desempeño', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('2',' Actas de Junta Directiva', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Boletines de Tesorería', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Certificado de Disponibilidad Presupuestal CDP', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('2','Certificado de Registro Presupuestal - RP', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Comprobante de Egreso', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('2','Comprobantes de Ingresos', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Consecutivos De Comunicaciones Oficiales', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Conciliaciones Bancarias', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Conceptos Jurídicos', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Contratos', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Convenio Interadministrativo', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('2','Convenio Interinstitucionales', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Cuentas Bancarias', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('2','Cuenta Por Cobrar', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Factura', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Historia Clínica', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('2','Historia Laboral', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('3','Historias de Equipos', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('','Historias de Equipos', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('','Historia Clínica Ocupacional', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Informes a Entes de Control y Vigilancia', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('2','informes de Gestion', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('3','Informes de Rendicion de Cuentas', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('','Banco Terminológico', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('','Plan Institucional de Archivo', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('','Programa de Gestion Documental', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('','Tablas de Control de Acceso', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('','Tablas de Retención Documental', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('','Tablas de Valoración Documental', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('','Inventarios Documentales', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Inventario General de Bienes', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Libros de Conteo Vacunas Diario', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('2','Libros Nota de Enfermería', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('3','Libro Auxiliar de Bancos', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('4','Libro Auxiliar de Caja', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('5','Libro Mayor y de Balance', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Licencia de Software', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Manual de Funciones', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('','Ordenes de Pago', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','P-DERECHOS DE PETICION DE INFORMACION', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('2','P-DERECHOS DE PETICION DE DOCUMENTOS', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('3','P-DERECHOS DE PETICION DE DOCUMENTOS- HISTORIA CLINICA', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('4','Q-QUEJA', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('5','R-RECLAMO RIESGO SIMPLE', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('6','R-RECLAMO RIESGO', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('7','R-RECLAMO RIESGO SIMPLE', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Plan de Accion', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Programa Institucional de Capacitacion PIC', 1);
INSERT INTO `archivo_trd_subserie` (`cod_subserie`, `nom_subserie`, `acti`) VALUES ('1','Proyectos de Inversión', 1);
