INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('Accion de tutela', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('Respuesta tutela', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('Acta', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('Acuerdos', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('balance', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('boletines', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('comprobante egreso', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('comprobante ingreso', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('concepto juridico', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('contrato', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('acta de inicio', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('poliza', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('estampillas', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('acta de liquidacion', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('factura', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('informe', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('anexos', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('soliciud', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('derecho de peticion', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('respuesta derecho de peticion', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('plan', 1);
INSERT INTO `archivo_trd_tipo_docu` (`nom_tipodoc`, `acti` ) VALUES ('programa', 1);
